stages:
  - build
  - test
  - deny

image: "rust:latest"

build:
  stage: build
  script:
    - cargo build --release

rustfmt:
    stage: test
    script:
        - cargo fmt --all --check

lint-test-job:
  stage: test
  script:
    - cargo clippy

include: 
  project: "internal/ci-catalog"
  ref: "main"
  file: "templates/cargo_deny.yml"

