stages:
  - build
  - test
  - deny

image: "rust:latest"

build:
  stage: build
  script:
    - cargo build --release

rustfmt:
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all --check
  needs: ["build"]

.install-clippy:
  before_script:
    - rustup component add clippy
  stage: test
  needs: ["build"]

lint-test-job:
  stage: test
  extends: .install-clippy
  script:
    - cargo clippy
  needs: ["build"]

include:
  project: "internal/ci-catalog"
  ref: "main"
  file: "templates/cargo_deny.yml"
  
  inputs:
    stage: deny


