services:
  discord-bot:
    container_name: f1-notif-bot
    restart: unless-stopped
    image: "codeberg.org/mto/f1-notif-bot:latest"
    env_file: ./.env
    volumes:
      - ./config/:/app/config
