[discord]
bot_token = "ODg2NTY0MTA1MzA0MDQ3NjI3.GMWqxs.MCyrOahTsVqGR5C0nt1n6YQNNw0wwWNFsEDrJ4"
guild = 883847530687913995
channel = 1002285400095719524

[mongo]
database_url = "localhost:27017"
database_user = "notificationsbot"
database_password = "abc"
database_name = "notifbot"
